# Generated by Django 2.0.5 on 2018-07-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiries',
            old_name='description',
            new_name='message',
        ),
        migrations.AddField(
            model_name='inquiries',
            name='cellphone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
