# Generated by Django 2.0.5 on 2018-07-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180707_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiries',
            name='Client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
