# Generated by Django 2.0.5 on 2018-07-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180707_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiries',
            old_name='Client_name',
            new_name='client_name',
        ),
    ]
