# Generated by Django 2.0.5 on 2018-07-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180708_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=204),
        ),
    ]
