# Generated by Django 2.0.5 on 2018-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_inquiries_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='payment_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiries',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
