# Generated by Django 2.0.5 on 2018-07-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiries',
            name='payment_info',
        ),
        migrations.AddField(
            model_name='inquiries',
            name='payment_status',
            field=models.CharField(choices=[(1, 'Yes'), (2, 'No')], default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='services',
            name='payment_info',
            field=models.CharField(default=914226, max_length=255),
        ),
    ]
