# Generated by Django 2.0.5 on 2018-07-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180716_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiries',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 1), ('Unpaid', 0)], default='Paid', max_length=3),
        ),
    ]
