# Generated by Django 2.0.5 on 2018-07-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180716_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiries',
            name='payment_status',
            field=models.BooleanField(choices=[('Paid', 1), ('Unpaid', 0)], default=1, max_length=3),
        ),
    ]
