# Generated by Django 2.0.5 on 2018-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180716_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='booked_time',
            field=models.DateTimeField(default='2018-07-15 15:30:00'),
        ),
    ]
