# Generated by Django 2.0.5 on 2018-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_inquiries_booked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='payment_info',
            field=models.CharField(default='Mpesa paybill number-914226', max_length=255),
        ),
    ]
