# Generated by Django 2.0.5 on 2018-07-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180717_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiries',
            name='time',
            field=models.TimeField(default='12:30:00'),
        ),
    ]
