# Generated by Django 2.2.7 on 2019-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20191112_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(blank=True, choices=[('Advertising', 'Advertising'), ('Automotive', 'Automotive'), ('Beauty', 'Beauty'), ('Car Rental', 'Car Rental'), ('Catering', 'Catering'), ('Cleaning', 'Cleaning'), ('Computer & IT', 'Computer & IT'), ('Event Planning', 'Event Planning'), ('Fitness', 'Fitness'), ('Interior Design', 'Interior Design'), ('Logistics', 'Logistics'), ('Massage Therapy', 'Massage Therapy'), ('Pet', 'Pet'), ('Photography & Video', 'Photography & Video'), ('Real Estate', 'Real Estate'), ('Renovation', 'Renovation'), ('Repair', 'Repair'), ('Travel Agencies', 'Travel Agencies'), ('Web Design', 'Web Design'), ('Wedding', 'Wedding'), ('Others', 'Others')], max_length=255, verbose_name='Category'),
        ),
    ]
